# Generated by Django 5.1.2 on 2024-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
