# Generated by Django 5.1.2 on 2024-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_letter', models.CharField(max_length=1, null=True)),
                ('class_number', models.IntegerField(null=True)),
                ('building_name', models.CharField(max_length=100)),
                ('floor_number', models.IntegerField()),
            ],
            options={
                'unique_together': {('grade_letter', 'class_number')},
            },
        ),
    ]
